name: Deploy

on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        run: |
          echo "VERSION=$(cat version)" >> $GITHUB_ENV
          echo "NEW_TAG=v$(cat version)" >> $GITHUB_ENV
      - name: Build and push Docker
        run: |
          docker build -t yourusername/python-app:${{ env.VERSION }} .
          docker push yourusername/python-app:${{ env.VERSION }}
      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
