name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq
          
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
           
      - name: Get Chrome version
        id: chrome-version
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
          echo "CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone-with-downloads.json | \
             jq -r ".milestones.\"${{ env.CHROME_MAJOR_VERSION }}\".version")
           
           [ -z "$CHROMEDRIVER_VERSION" ] || [ "$CHROMEDRIVER_VERSION" = "null" ] && CHROMEDRIVER_VERSION=${{ env.CHROME_VERSION }}
           
           echo "Installing ChromeDriver $CHROMEDRIVER_VERSION"
           wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
           unzip chromedriver-linux64.zip -d chromedriver
           sudo mv chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/

      - name: Verify installations
        run: |
          google-chrome-stable --version
          chromedriver --version
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager allure-pytest pytest-cov bandit safety
          
      - name: Run tests
        run: |
          pytest tests/ --cov=src/ --alluredir=allure-results
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
