name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo rm -f /usr/bin/google-chrome
          sudo rm -f /usr/bin/chromedriver
          
          sudo apt-get install -y wget
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=${CHROME_VERSION%.*.*}
          wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION} -O chromedriver-version.txt
          CHROME_DRIVER_VERSION=$(cat chromedriver-version.txt)
          wget -q https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          sudo unzip -o chromedriver_linux64.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip chromedriver-version.txt
          
          google-chrome-stable --version
          chromedriver --version
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest-allure
          
      - name: Run tests
        run: |
          pytest tests/ --cov=src/ --alluredir=allure-results
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
        if: always()
