name: Update Version

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        id: bump
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') && 'patch' || 'minor' }}

      - name: Update version file
        run: |
          echo "${{ steps.bump.outputs.new_tag }}" | sed 's/v//' > version
          git add version
          git commit -m "[${{ steps.bump.outputs.new_tag }}] Version bump"
          git push
