name: Version Update

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update version
        id: version
        run: |
          cd .github/scripts/
          NEW_VERSION=$(python version_manager.py patch)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version file
        run: |
          echo "New version: ${{ steps.version.outputs.new_version }}"
